"""FastAPI service exposing flagged events and summary stats for the
dashboard (Phase 3). Read-only — all writes happen in the consumer.

Run with: uvicorn api.main:app --reload --port 8000
(from the project root, with the venv active)

Interactive API docs are auto-generated by FastAPI at /docs.
"""
import os
import sys
from typing import List

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_THIS_DIR)
sys.path.append(_PROJECT_ROOT)

from db.session import get_engine  # noqa: E402
from api.schemas import (  # noqa: E402
    FlaggedEventOut,
    SummaryStatsOut,
    ReasonCount,
    TimeseriesPoint,
)

load_dotenv()

app = FastAPI(title="Fraud Detection Dashboard API")

# Local dev only: Streamlit (port 8501) calling FastAPI (port 8000) is a
# cross-origin request from the browser's perspective. Wide open here
# because this never leaves localhost in this project's scope.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

engine = get_engine()


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/flagged-events", response_model=List[FlaggedEventOut])
def get_flagged_events(limit: int = 50, offset: int = 0):
    query = text(
        """
        SELECT
            fe.id,
            fe.transaction_id,
            t.user_id,
            t.amount,
            t.merchant_category,
            fe.reason,
            fe.rule_types,
            fe.score,
            fe.flagged_at
        FROM flagged_events fe
        JOIN transactions t ON t.id = fe.transaction_id
        ORDER BY fe.flagged_at DESC
        LIMIT :limit OFFSET :offset
        """
    )
    with engine.connect() as conn:
        rows = conn.execute(query, {"limit": limit, "offset": offset}).mappings().all()
    return [
        FlaggedEventOut(
            id=str(r["id"]),
            transaction_id=str(r["transaction_id"]),
            user_id=r["user_id"],
            amount=float(r["amount"]),
            merchant_category=r["merchant_category"],
            reason=r["reason"],
            rule_types=r["rule_types"] or [],
            score=r["score"],
            flagged_at=r["flagged_at"],
        )
        for r in rows
    ]


@app.get("/stats/summary", response_model=SummaryStatsOut)
def get_summary():
    with engine.connect() as conn:
        total_transactions = conn.execute(text("SELECT count(*) FROM transactions")).scalar()
        total_flagged = conn.execute(text("SELECT count(*) FROM flagged_events")).scalar()
        avg_score = conn.execute(text("SELECT coalesce(avg(score), 0) FROM flagged_events")).scalar()

    flag_rate = (total_flagged / total_transactions) if total_transactions else 0.0
    return SummaryStatsOut(
        total_transactions=total_transactions,
        total_flagged=total_flagged,
        flag_rate=flag_rate,
        avg_flagged_score=float(avg_score),
    )


@app.get("/stats/top-reasons", response_model=List[ReasonCount])
def get_top_reasons(limit: int = 5):
    # rule_types is a TEXT[] per event (a transaction can trigger multiple
    # rules at once) -- unnest() flattens that into one row per rule so we
    # can group cleanly. See BUILD_LOG.md, Phase 3, for why this couldn't
    # be done against the original free-text `reason` column.
    query = text(
        """
        SELECT unnest(rule_types) AS rule_type, count(*) AS count
        FROM flagged_events
        GROUP BY rule_type
        ORDER BY count DESC
        LIMIT :limit
        """
    )
    with engine.connect() as conn:
        rows = conn.execute(query, {"limit": limit}).mappings().all()
    return [ReasonCount(rule_type=r["rule_type"], count=r["count"]) for r in rows]


@app.get("/stats/timeseries", response_model=List[TimeseriesPoint])
def get_timeseries(window_minutes: int = 120, bucket_minutes: int = 5):
    """Flagged vs. total transaction counts, bucketed into fixed-width time
    windows. Buckets are aligned to Unix-epoch boundaries (floor(epoch /
    bucket_seconds)) rather than to "now", so bucket edges are stable and
    reproducible instead of shifting on every request -- a small detail
    that matters if you ever compare two timeseries calls made a few
    seconds apart. This also avoids needing a Postgres extension (e.g.
    TimescaleDB's time_bucket()) for what's otherwise a two-line function.
    """
    bucket_seconds = max(1, bucket_minutes) * 60
    query = text(
        """
        WITH bounds AS (
            SELECT
                to_timestamp(floor(extract(epoch FROM now() - (:window_minutes || ' minutes')::interval) / :bucket_seconds) * :bucket_seconds) AS start_bucket,
                to_timestamp(floor(extract(epoch FROM now()) / :bucket_seconds) * :bucket_seconds) AS end_bucket
        ),
        buckets AS (
            SELECT generate_series(start_bucket, end_bucket, (:bucket_seconds || ' seconds')::interval) AS bucket_start
            FROM bounds
        ),
        totals AS (
            SELECT
                to_timestamp(floor(extract(epoch FROM "timestamp") / :bucket_seconds) * :bucket_seconds) AS bucket_start,
                count(*) AS total_count
            FROM transactions
            WHERE "timestamp" >= now() - (:window_minutes || ' minutes')::interval
            GROUP BY 1
        ),
        flagged AS (
            SELECT
                to_timestamp(floor(extract(epoch FROM flagged_at) / :bucket_seconds) * :bucket_seconds) AS bucket_start,
                count(*) AS flagged_count
            FROM flagged_events
            WHERE flagged_at >= now() - (:window_minutes || ' minutes')::interval
            GROUP BY 1
        )
        SELECT
            b.bucket_start,
            COALESCE(f.flagged_count, 0) AS flagged_count,
            COALESCE(t.total_count, 0) AS total_count
        FROM buckets b
        LEFT JOIN totals t ON t.bucket_start = b.bucket_start
        LEFT JOIN flagged f ON f.bucket_start = b.bucket_start
        ORDER BY b.bucket_start
        """
    )
    with engine.connect() as conn:
        rows = conn.execute(
            query, {"window_minutes": window_minutes, "bucket_seconds": bucket_seconds}
        ).mappings().all()
    return [
        TimeseriesPoint(bucket_start=r["bucket_start"], flagged_count=r["flagged_count"], total_count=r["total_count"])
        for r in rows
    ]
